/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import DAO.Connect;
import DAO.KhoaDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author NguyenAnhPhan
 */
public class QLGiangVien extends javax.swing.JPanel {

    public static Connection conn = Connect.getConnect();
    public static PreparedStatement pst, pst1 = null;
    public static ResultSet rs, rs1 = null;
    public static Statement st = null;

    public QLGiangVien() {
        initComponents();
        listItem();
    }

    public void listItem() {
        String query1 = "select TenKhoa from Khoa order by TenKhoa asc";
        String query2 = "select TenChucVu from ChucVu order by TenChucVu asc";
        String query3 = "select HocHam from HocHamHocVi order by HocHam asc";

        KhoaDAO.LoadCombobx(query1, cbxThemKhoa1, "TenKhoa");
        KhoaDAO.LoadCombobx(query2, cbxThemChucVu1, "TenChucVu");
        KhoaDAO.LoadCombobx(query3, cbxThemHHHV1, "HocHam");

        String checkKhoa = cbxThemKhoa1.getSelectedItem().toString();
        String query4 = "select TenBM from BoMon where TenKhoa = N'" + checkKhoa + "'";
        KhoaDAO.LoadCombobx(query4, cbxThemBoMon1, "TenBM");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txtThemMaGV1 = new javax.swing.JTextField();
        txtThemTenGV1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtThemNamSinh1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        rdbThemNam1 = new javax.swing.JRadioButton();
        rdbThemNu1 = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        cbxThemHHHV1 = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        txtThemLuongThucNhan1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        cbxThemKhoa1 = new javax.swing.JComboBox<>();
        cbxThemBoMon1 = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        passThemMatKhau1 = new javax.swing.JPasswordField();
        jLabel30 = new javax.swing.JLabel();
        passThemNhapLaiMK1 = new javax.swing.JPasswordField();
        cbxThemChucVu1 = new javax.swing.JComboBox<>();
        btnThenSuaGV1 = new javax.swing.JButton();
        btnThemXoaGV1 = new javax.swing.JButton();
        btnThemGV1 = new javax.swing.JButton();
        btnTimKiemGV1 = new javax.swing.JButton();
        txtThemTimKiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableGV1 = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(570, 500));

        jTabbedPane1.setFocusable(false);
        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(700, 500));

        jLabel20.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel20.setText("Mã giảng viên");

        jLabel21.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel21.setText("Tên giảng viên");

        jLabel22.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel22.setText("Năm sinh");

        jLabel23.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel23.setText("Chức vụ");

        jLabel24.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel24.setText("Giới tính");

        rdbThemNam1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rdbThemNam1.setText("Nam");

        rdbThemNu1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rdbThemNu1.setText("Nữ");

        jLabel25.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel25.setText("Học hàm - Học vị");

        jLabel26.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel26.setText("Lương thực nhận");

        jLabel27.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel27.setText("Khoa");

        cbxThemKhoa1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbxThemKhoa1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxThemKhoa1ItemStateChanged(evt);
            }
        });

        cbxThemBoMon1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbxThemBoMon1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel28.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel28.setText("Bộ môn");

        jLabel29.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel29.setText("Mật khẩu");

        jLabel30.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel30.setText("Nhập lại mật khẩu");

        cbxThemChucVu1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        btnThenSuaGV1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThenSuaGV1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit.png"))); // NOI18N
        btnThenSuaGV1.setText("Sửa");

        btnThemXoaGV1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThemXoaGV1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn_delete.png"))); // NOI18N
        btnThemXoaGV1.setText("Xóa");

        btnThemGV1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThemGV1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn_add.png"))); // NOI18N
        btnThemGV1.setText("Thêm");
        btnThemGV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemGV1ActionPerformed(evt);
            }
        });

        btnTimKiemGV1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTimKiemGV1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn_search.png"))); // NOI18N
        btnTimKiemGV1.setText("Tìm kiếm");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(jLabel22)
                            .addComponent(jLabel24)
                            .addComponent(jLabel26))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(rdbThemNam1)
                                .addGap(18, 18, 18)
                                .addComponent(rdbThemNu1))
                            .addComponent(txtThemMaGV1)
                            .addComponent(passThemMatKhau1)
                            .addComponent(passThemNhapLaiMK1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(txtThemNamSinh1)
                            .addComponent(txtThemLuongThucNhan1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(txtThemTimKiem)
                        .addGap(18, 18, 18)
                        .addComponent(btnTimKiemGV1)))
                .addGap(35, 35, 35)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtThemTenGV1))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxThemKhoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxThemBoMon1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxThemChucVu1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxThemHHHV1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(btnThemGV1)
                        .addGap(18, 18, 18)
                        .addComponent(btnThenSuaGV1)
                        .addGap(18, 18, 18)
                        .addComponent(btnThemXoaGV1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbxThemBoMon1, cbxThemChucVu1, cbxThemHHHV1, cbxThemKhoa1, passThemMatKhau1, passThemNhapLaiMK1, txtThemLuongThucNhan1, txtThemMaGV1, txtThemNamSinh1, txtThemTenGV1});

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel20, jLabel21, jLabel23, jLabel25, jLabel27, jLabel28, jLabel29, jLabel30});

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnThemGV1, btnThemXoaGV1, btnThenSuaGV1, btnTimKiemGV1});

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel22, jLabel24, jLabel26});

        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtThemMaGV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(txtThemTenGV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(passThemMatKhau1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(cbxThemKhoa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(passThemNhapLaiMK1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(cbxThemBoMon1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtThemNamSinh1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(cbxThemChucVu1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(rdbThemNam1)
                    .addComponent(rdbThemNu1)
                    .addComponent(jLabel25)
                    .addComponent(cbxThemHHHV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtThemLuongThucNhan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemXoaGV1)
                    .addComponent(btnThenSuaGV1)
                    .addComponent(btnThemGV1)
                    .addComponent(btnTimKiemGV1)
                    .addComponent(txtThemTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbxThemBoMon1, cbxThemChucVu1, passThemMatKhau1, passThemNhapLaiMK1, txtThemMaGV1, txtThemTenGV1});

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbxThemHHHV1, txtThemLuongThucNhan1, txtThemNamSinh1});

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel20, jLabel21, jLabel23, jLabel27, jLabel28, jLabel29, jLabel30});

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel22, jLabel24, jLabel25, jLabel26});

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnThemGV1, btnThemXoaGV1, btnThenSuaGV1});

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách giảng viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jTableGV1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableGV1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thông tin giảng viên", new javax.swing.ImageIcon(getClass().getResource("/Images/contact-new.png")), jPanel5); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemGV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemGV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemGV1ActionPerformed

    private void cbxThemKhoa1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxThemKhoa1ItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbxThemKhoa1ItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThemGV1;
    private javax.swing.JButton btnThemXoaGV1;
    private javax.swing.JButton btnThenSuaGV1;
    private javax.swing.JButton btnTimKiemGV1;
    private javax.swing.JComboBox<String> cbxThemBoMon1;
    private javax.swing.JComboBox<String> cbxThemChucVu1;
    private javax.swing.JComboBox<String> cbxThemHHHV1;
    private javax.swing.JComboBox<String> cbxThemKhoa1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableGV1;
    private javax.swing.JPasswordField passThemMatKhau1;
    private javax.swing.JPasswordField passThemNhapLaiMK1;
    private javax.swing.JRadioButton rdbThemNam1;
    private javax.swing.JRadioButton rdbThemNu1;
    private javax.swing.JTextField txtThemLuongThucNhan1;
    private javax.swing.JTextField txtThemMaGV1;
    private javax.swing.JTextField txtThemNamSinh1;
    private javax.swing.JTextField txtThemTenGV1;
    private javax.swing.JTextField txtThemTimKiem;
    // End of variables declaration//GEN-END:variables
}
